@host=http://localhost:3000

####
GET {{host}}/api/admin


####
GET {{host}}/api/admin/131
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMzEsInVzZXJfcm9sZSI6ImFkbWluIiwiZXhwIjoxNjg3NTMwMDIxLCJpYXQiOjE2ODY5MjUyMjF9.k0PXaNlcrO_DUYSl5CLo9S4rHHaxJ5ojU-Q4v7R2Krg

####
POST {{host}}/api/admin
Content-Type: application/json

{
  "role_id": 1,
  "username": "admin",
  "email": "admin@gmail.com",
  "password": "12345678",
  "first_name": "Lucia",
  "last_name": "Fuentes"
}

#####
PUT {{host}}/api/admin/95
Content-Type: application/json

{
  "role_id": 1,
  "username": "Alba",
  "email": "alba@gmail.com",
  "password": "12345678",
  "first_name": "Alba",
  "last_name": "Santana"
}

#####
DELETE {{host}}/api/admin/70
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxODc5LCJ1c2VyX3JvbGUiOiJhZG1pbiIsImV4cCI6MTY4NzQzMzgwMiwiaWF0IjoxNjg2ODI5MDAyfQ.BFwvQOQKi4OL5XrSd-tcmhpQVr-be307qKlAg6C2RPA


#####
DELETE {{host}}/api/admin
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMzEsInVzZXJfcm9sZSI6ImFkbWluIiwiZXhwIjoxNjg2OTMxNDU1LCJpYXQiOjE2ODYzMjY2NTV9.CLnIF88w3HYAXDV6sL9sKXuZbL6ggOw2JE36u-XkcSg


#####
PUT {{host}}/api/admin/validate/3
Content-Type: application/json

{
    "is_approved": 1
}

####
PUT {{host}}/api/admin/deactive/40
Content-Type: application/json

{
    "is_active": 0
}