@host=http://localhost:3000

##### admin
POST {{host}}/users/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "12345678"
}

##### Student
POST {{host}}/users/login
Content-Type: application/json

{
    "email": "llopez5@gmail.com",
    "password": "laurita12"
}

##### Teacher
POST {{host}}/users/login
Content-Type: application/json

{
    "email": "fgarcia157@gmail.com",
    "password": "12345678"
}
