@host=http://localhost:3000

##### admi
POST {{host}}/users/login
Content-Type: application/json

{
    "email": "alba@gmail.com",
    "password": "12345678"
}

##### Student
POST {{host}}/users/login
Content-Type: application/json

{
    "email": "jose@gmail.com",
    "password": "12345678"
}

##### Teacher
POST {{host}}/users/login
Content-Type: application/json

{
    "email": "luis@outlook.com",
    "password": "23Luis1"
}
