@host=http://localhost:3000

GET {{host}}/api/reviews/45

#####
POST {{host}}/api/reviews
Content-Type: application/json

{
    "teachers_id":98, 
    "students_id": 110, 
    "rating": 4, 
    "comment": "Muy profesional, se nota que le gusta enseñar"
}

#####
PUT {{host}}/api/reviews/32
Content-Type: application/json

{
    "teachers_id":2, 
    "students_id": 4, 
    "rating": 3, 
    "comment": "Muy profesional, se nota que le gusta enseñar"
}

#####
GET {{host}}/api/reviews?teacherid=100&studentid=10

#####
GET {{host}}/api/reviews/student/34

#####
GET {{host}}/api/reviews/teacher/100