@host=http://localhost:3000
####
GET {{host}}/api/teachers

###### /** GET a teacher by ID with avg_rating*/
GET {{host}}/api/teachers/109

###
GET {{host}}/api/teachers/hours/107

##### order by price_hour asc, experience desc
GET {{host}}/api/teachers/filters/1

##### order by categories_id, price_hour asc, experience desc
GET {{host}}/api/teachers/filters/2

#####order by teacher_id
GET {{host}}/api/teachers/filters/3

#####
POST {{host}}/api/teachers
Content-Type: application/json

{
  "first_name": "Federico",
  "last_name": "Garcia",
  "username": "fgarcia157",
  "email": "fgarcia157@gmail.com",
  "password": "12345678",
  "role_id": 2,
  "phone": "678234642",
  "avatar":"https://i.pravatar.cc/500?u=ernesto.alanizcorral@peticiones.online",
  "latitude": -34,
  "longitude": -3,
  "city_id": 3,
  "address": "Gran Via 23",
  "price_hour": 10,
  "experience": 5,
  "category_id": 1,
  "subject": "Intro to Maths",
  "is_approved": 0,
  "start_class_hour": 8,
  "end_class_hour":10
}

####
PUT {{host}}/api/teachers/132
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMTcsInVzZXJfcm9sZSI6InRlYWNoZXIiLCJleHAiOjE2ODc5NTM3MDcsImlhdCI6MTY4NzM0ODkwN30.jIW5S7RjMZEqEPPzC-ky_kREVVYukp2qXwp5TLi2vkg

{
  "first_name": "Federico",
  "last_name": "García",
  "username": "fgarcia157",
  "email": "fgarcia157@gmail.com",
  "password": "12345678",
  "role_id": 2,
 "phone": "123468025",
 "avatar":"https://i.pravatar.cc/500?u=mariadelcarmen.herreravillanueva@peticiones.online",
 "latitude": -34,
 "longitude": -3,
 "city_id": 6,
 "address": "Av Federico García Lorca 2",
  "price_hour": 30,
  "experience": 20,
  "category_id": 9,
  "subject": "Visual Arts",
  "is_approved": 0,
  "start_class_hour": 10,
  "end_class_hour":12
}

####
PUT {{host}}/api/teachers/validate/115

####
DELETE {{host}}/api/teachers/21