@host=http://localhost:3000

#### USERS #######
GET {{host}}/users

###### API USERS ########
GET {{host}}/api/users

#####
GET {{host}}/api/users/5

####
GET {{host}}/api/users/email/op50@gmail.com

####
POST {{host}}/api/users
Content-Type: application/json

{
    "role_id": 5,
    "username": "Julita",
    "email": "juli5@gmail.com",
    "password": "Julita*2",
    "first_name": "Julia",
    "last_name": "García"
}

####
PUT {{host}}/api/users/1
Content-Type: application/json

{
    "role_id": 5,
    "username": "Julita",
    "email": "juli5@gmail.com",
    "password": "Julita*26",
    "first_name": "Julia",
    "last_name": "García"
}

######
DELETE {{host}}/api/users/98

####
PUT {{host}}/api/users/location/97
Content-Type: application/json

{
    "role": "student",
    "latitude": -3,
    "longitude": -1
}